openapi: 3.0.0
info:
  title: genai-v1-summarize
  description: genai-v1-summarize
  version: 1.0.0
servers:
 - url: https://dev.35.227.240.213.nip.io/v1/genai
paths:
  /summarize:
    post:
      operationId: summarize
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/inputPdfPayload"
      responses:
        "200":
          description: The summarized PDF document.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/outputPdfPayload"
        "400":
          description: The request body is invalid.
      summary: Summarizes a PDF document.
components:
  schemas:
    inputPdfPayload:
      description: The base64 representation of the PDF document.
      properties:
        pdfBase64:
          type: string
      type: object
    outputPdfPayload:
      description: The string summary of the PDF document.
      type: object
      properties:
        summary:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: query
security:
  - api_key: []
